import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

try:
    from PyQt5.QtWidgets import (
        QWidget, QVBoxLayout, QHBoxLayout, QTabWidget, QFormLayout,
        QLineEdit, QPushButton, QLabel, QComboBox, QCheckBox,
        QSlider, QGroupBox, QMessageBox, QSpinBox, QDoubleSpinBox,
        QFileDialog, QTextEdit, QProgressBar
    )
    from PyQt5.QtCore import Qt, QTimer
    PYQT5_AVAILABLE = True
except ImportError:
    PYQT5_AVAILABLE = False

from .manager import SettingsManager, get_settings_manager
from .config import ConfigValidator

class SettingsWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.settings_mgr = get_settings_manager()
        self.init_ui()
        self.load_settings()
    
    def init_ui(self):
        layout = QVBoxLayout()
        layout.setContentsMargins(10, 10, 10, 10)
        self.tabs = QTabWidget()
        self.tabs.addTab(self._create_feishu_tab(), '飞书配置')
        self.tabs.addTab(self._create_map_tab(), '地图配置')
        self.tabs.addTab(self._create_crawler_tab(), '爬虫配置')
        self.tabs.addTab(self._create_alert_tab(), '预警规则')
        self.tabs.addTab(self._create_data_tab(), '数据目录')
        self.tabs.addTab(self._create_ai_tab(), 'AI模型')
        layout.addWidget(self.tabs)
        self.setLayout(layout)
    
    def _create_feishu_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置飞书机器人用于推送消息到群聊')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        form = QFormLayout()
        self.feishu_app_id = QLineEdit()
        self.feishu_app_id.setPlaceholderText('请输入飞书 App ID')
        form.addRow('App ID:', self.feishu_app_id)
        self.feishu_app_secret = QLineEdit()
        self.feishu_app_secret.setPlaceholderText('请输入飞书 App Secret')
        self.feishu_app_secret.setEchoMode(QLineEdit.Password)
        form.addRow('App Secret:', self.feishu_app_secret)
        self.feishu_channel_id = QLineEdit()
        self.feishu_channel_id.setPlaceholderText('接收消息的群ID或open_id')
        form.addRow('接收群ID:', self.feishu_channel_id)
        self.feishu_enabled = QCheckBox('启用飞书推送')
        form.addRow('', self.feishu_enabled)
        layout.addLayout(form)
        btn_layout = QHBoxLayout()
        self.btn_test_feishu = QPushButton('测试连接')
        self.btn_test_feishu.clicked.connect(self._test_feishu)
        btn_layout.addWidget(self.btn_test_feishu)
        self.btn_save_feishu = QPushButton('保存配置')
        self.btn_save_feishu.clicked.connect(self._save_feishu)
        btn_layout.addWidget(self.btn_save_feishu)
        self.btn_reset_feishu = QPushButton('重置')
        self.btn_reset_feishu.clicked.connect(self._reset_feishu)
        btn_layout.addWidget(self.btn_reset_feishu)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        self.feishu_status = QLabel('')
        self.feishu_status.setStyleSheet('color: #0078d4; padding: 5px;')
        layout.addWidget(self.feishu_status)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _create_map_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置地图服务提供商')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        form = QFormLayout()
        self.map_provider = QComboBox()
        self.map_provider.addItems(['amap', 'tianditu', 'osm'])
        self.map_provider.currentTextChanged.connect(self._on_map_provider_changed)
        form.addRow('底图服务:', self.map_provider)
        self.amap_key = QLineEdit()
        self.amap_key.setPlaceholderText('高德地图 API Key')
        form.addRow('高德 Key:', self.amap_key)
        self.tianditu_key = QLineEdit()
        self.tianditu_key.setPlaceholderText('天地图 API Key')
        form.addRow('天地图 Key:', self.tianditu_key)
        layout.addLayout(form)
        btn_layout = QHBoxLayout()
        self.btn_test_map = QPushButton('验证 Key')
        self.btn_test_map.clicked.connect(self._test_map)
        btn_layout.addWidget(self.btn_test_map)
        self.btn_save_map = QPushButton('保存配置')
        self.btn_save_map.clicked.connect(self._save_map)
        btn_layout.addWidget(self.btn_save_map)
        self.btn_reset_map = QPushButton('重置')
        self.btn_reset_map.clicked.connect(self._reset_map)
        btn_layout.addWidget(self.btn_reset_map)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        self.map_status = QLabel('')
        self.map_status.setStyleSheet('color: #0078d4; padding: 5px;')
        layout.addWidget(self.map_status)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _create_crawler_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置数据爬取频率和来源')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        self.crawler_enabled = QCheckBox('启用数据爬取')
        layout.addWidget(self.crawler_enabled)
        freq_group = QGroupBox('更新频率')
        freq_layout = QVBoxLayout()
        self.crawler_interval = QSlider(Qt.Horizontal)
        self.crawler_interval.setMinimum(1)
        self.crawler_interval.setMaximum(6)
        self.crawler_interval.setTickPosition(QSlider.TicksBelow)
        self.crawler_interval.setTickInterval(1)
        self.crawler_interval.valueChanged.connect(self._on_interval_changed)
        freq_layout.addWidget(self.crawler_interval)
        self.interval_label = QLabel('当前: 3 小时')
        self.interval_label.setAlignment(Qt.AlignCenter)
        freq_layout.addWidget(self.interval_label)
        freq_group.setLayout(freq_layout)
        layout.addWidget(freq_group)
        sources_group = QGroupBox('数据来源')
        sources_layout = QVBoxLayout()
        self.source_baidu = QCheckBox('百度新闻')
        sources_layout.addWidget(self.source_baidu)
        self.source_sina = QCheckBox('新浪军事')
        sources_layout.addWidget(self.source_sina)
        self.source_163 = QCheckBox('网易军事')
        sources_layout.addWidget(self.source_163)
        self.source_xiangshan = QCheckBox('铁血社区')
        sources_layout.addWidget(self.source_xiangshan)
        sources_group.setLayout(sources_layout)
        layout.addWidget(sources_group)
        btn_layout = QHBoxLayout()
        self.btn_save_crawler = QPushButton('保存配置')
        self.btn_save_crawler.clicked.connect(self._save_crawler)
        btn_layout.addWidget(self.btn_save_crawler)
        self.btn_reset_crawler = QPushButton('重置')
        self.btn_reset_crawler.clicked.connect(self._reset_crawler)
        btn_layout.addWidget(self.btn_reset_crawler)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _create_alert_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置预警触发条件和严重程度阈值')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        self.alert_enabled = QCheckBox('启用预警通知')
        layout.addWidget(self.alert_enabled)
        form = QFormLayout()
        high_layout = QHBoxLayout()
        self.alert_high = QDoubleSpinBox()
        self.alert_high.setMinimum(1)
        self.alert_high.setMaximum(10)
        self.alert_high.setSingleStep(0.5)
        self.alert_high.setDecimals(1)
        high_layout.addWidget(self.alert_high)
        high_layout.addWidget(QLabel('分 (1-10)'))
        high_layout.addStretch()
        form.addRow('高风险阈值:', high_layout)
        medium_layout = QHBoxLayout()
        self.alert_medium = QDoubleSpinBox()
        self.alert_medium.setMinimum(1)
        self.alert_medium.setMaximum(10)
        self.alert_medium.setSingleStep(0.5)
        self.alert_medium.setDecimals(1)
        medium_layout.addWidget(self.alert_medium)
        medium_layout.addWidget(QLabel('分 (1-10)'))
        medium_layout.addStretch()
        form.addRow('中风险阈值:', medium_layout)
        layout.addLayout(form)
        desc = QLabel('预警评分根据新闻关键词、来源可信度等综合计算')
        desc.setStyleSheet('color: #888; font-size: 12px;')
        layout.addWidget(desc)
        btn_layout = QHBoxLayout()
        self.btn_save_alert = QPushButton('保存配置')
        self.btn_save_alert.clicked.connect(self._save_alert)
        btn_layout.addWidget(self.btn_save_alert)
        self.btn_reset_alert = QPushButton('重置')
        self.btn_reset_alert.clicked.connect(self._reset_alert)
        btn_layout.addWidget(self.btn_reset_alert)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _create_data_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置数据存储路径')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        form = QFormLayout()
        obs_layout = QHBoxLayout()
        self.obsidian_path = QLineEdit()
        self.obsidian_path.setPlaceholderText('~/ObsidianVault')
        obs_layout.addWidget(self.obsidian_path)
        btn_obs = QPushButton('浏览')
        btn_obs.clicked.connect(lambda: self._browse_path(self.obsidian_path))
        obs_layout.addWidget(btn_obs)
        form.addRow('Obsidian路径:', obs_layout)
        db_layout = QHBoxLayout()
        self.db_path = QLineEdit()
        self.db_path.setPlaceholderText('~/projects/global-military-monitor/data')
        db_layout.addWidget(self.db_path)
        btn_db = QPushButton('浏览')
        btn_db.clicked.connect(lambda: self._browse_path(self.db_path))
        db_layout.addWidget(btn_db)
        form.addRow('数据库路径:', db_layout)
        backup_layout = QHBoxLayout()
        self.backup_path = QLineEdit()
        self.backup_path.setPlaceholderText('~/projects/global-military-monitor/backups')
        backup_layout.addWidget(self.backup_path)
        btn_backup = QPushButton('浏览')
        btn_backup.clicked.connect(lambda: self._browse_path(self.backup_path))
        backup_layout.addWidget(btn_backup)
        form.addRow('备份目录:', backup_layout)
        layout.addLayout(form)
        export_layout = QHBoxLayout()
        btn_export = QPushButton('导出配置到 .env')
        btn_export.clicked.connect(self._export_config)
        export_layout.addWidget(btn_export)
        export_layout.addStretch()
        layout.addLayout(export_layout)
        btn_layout = QHBoxLayout()
        self.btn_save_data = QPushButton('保存配置')
        self.btn_save_data.clicked.connect(self._save_data)
        btn_layout.addWidget(self.btn_save_data)
        self.btn_reset_data = QPushButton('重置')
        self.btn_reset_data.clicked.connect(self._reset_data)
        btn_layout.addWidget(self.btn_reset_data)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _create_ai_tab(self):
        widget = QWidget()
        layout = QVBoxLayout()
        info = QLabel('配置AI模型用于新闻分析和摘要生成')
        info.setStyleSheet('color: #666; padding: 5px;')
        layout.addWidget(info)
        form = QFormLayout()
        self.ai_model = QComboBox()
        self.ai_model.addItems(['minimax', 'openai', 'zhipu', 'dashscope'])
        form.addRow('AI 模型:', self.ai_model)
        self.ai_api_key = QLineEdit()
        self.ai_api_key.setPlaceholderText('输入 API Key')
        self.ai_api_key.setEchoMode(QLineEdit.Password)
        form.addRow('API Key:', self.ai_api_key)
        temp_layout = QHBoxLayout()
        self.ai_temperature = QDoubleSpinBox()
        self.ai_temperature.setMinimum(0)
        self.ai_temperature.setMaximum(1)
        self.ai_temperature.setSingleStep(0.1)
        self.ai_temperature.setDecimals(1)
        temp_layout.addWidget(self.ai_temperature)
        temp_layout.addWidget(QLabel('(0=精确, 1=创意)'))
        temp_layout.addStretch()
        form.addRow('温度参数:', temp_layout)
        layout.addLayout(form)
        btn_layout = QHBoxLayout()
        self.btn_test_ai = QPushButton('测试连接')
        self.btn_test_ai.clicked.connect(self._test_ai)
        btn_layout.addWidget(self.btn_test_ai)
        self.btn_save_ai = QPushButton('保存配置')
        self.btn_save_ai.clicked.connect(self._save_ai)
        btn_layout.addWidget(self.btn_save_ai)
        self.btn_reset_ai = QPushButton('重置')
        self.btn_reset_ai.clicked.connect(self._reset_ai)
        btn_layout.addWidget(self.btn_reset_ai)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)
        self.ai_status = QLabel('')
        self.ai_status.setStyleSheet('color: #0078d4; padding: 5px;')
        layout.addWidget(self.ai_status)
        layout.addStretch()
        widget.setLayout(layout)
        return widget
    
    def _on_map_provider_changed(self, provider):
        pass
    
    def _on_interval_changed(self, value):
        self.interval_label.setText(f'当前: {value} 小时')
    
    def _browse_path(self, line_edit):
        path = QFileDialog.getExistingDirectory(self, '选择目录', line_edit.text() or os.path.expanduser('~'))
        if path:
            line_edit.setText(path)
    
    def load_settings(self):
        self.feishu_app_id.setText(self.settings_mgr.get('feishu_app_id', ''))
        self.feishu_app_secret.setText(self.settings_mgr.get('feishu_app_secret', ''))
        self.feishu_channel_id.setText(self.settings_mgr.get('feishu_receive_channel_id', ''))
        self.feishu_enabled.setChecked(self.settings_mgr.get('feishu_enabled', False))
        self.map_provider.setCurrentText(self.settings_mgr.get('map_provider', 'amap'))
        self.amap_key.setText(self.settings_mgr.get('amap_key', ''))
        self.tianditu_key.setText(self.settings_mgr.get('tianditu_key', ''))
        self.crawler_enabled.setChecked(self.settings_mgr.get('crawler_enabled', True))
        self.crawler_interval.setValue(int(self.settings_mgr.get('crawler_interval_hours', 3)))
        sources = self.settings_mgr.get('crawler_sources', {})
        self.source_baidu.setChecked(sources.get('baidu', True))
        self.source_sina.setChecked(sources.get('sina', True))
        self.source_163.setChecked(sources.get('163', True))
        self.source_xiangshan.setChecked(sources.get('xiangshan', True))
        self.alert_enabled.setChecked(self.settings_mgr.get('alert_enabled', True))
        self.alert_high.setValue(float(self.settings_mgr.get('alert_high_threshold', 7)))
        self.alert_medium.setValue(float(self.settings_mgr.get('alert_medium_threshold', 4)))
        self.obsidian_path.setText(self.settings_mgr.get('obsidian_path', ''))
        self.db_path.setText(self.settings_mgr.get('db_path', ''))
        self.backup_path.setText(self.settings_mgr.get('backup_path', ''))
        self.ai_model.setCurrentText(self.settings_mgr.get('ai_model', 'minimax'))
        self.ai_api_key.setText(self.settings_mgr.get('ai_api_key', ''))
        self.ai_temperature.setValue(float(self.settings_mgr.get('ai_temperature', 0.7)))
    
    def _test_feishu(self):
        success, msg = ConfigValidator.validate_feishu(self.feishu_app_id.text(), self.feishu_app_secret.text())
        self.feishu_status.setText(msg)
        self.feishu_status.setStyleSheet('color: green;' if success else 'color: red;')
    
    def _save_feishu(self):
        self.settings_mgr.save('feishu_app_id', self.feishu_app_id.text())
        self.settings_mgr.save('feishu_app_secret', self.feishu_app_secret.text())
        self.settings_mgr.save('feishu_receive_channel_id', self.feishu_channel_id.text())
        self.settings_mgr.save('feishu_enabled', self.feishu_enabled.isChecked())
        QMessageBox.information(self, '保存成功', '飞书配置已保存')
    
    def _reset_feishu(self):
        self.settings_mgr.reset_to_default('feishu_app_id')
        self.settings_mgr.reset_to_default('feishu_app_secret')
        self.settings_mgr.reset_to_default('feishu_receive_channel_id')
        self.settings_mgr.reset_to_default('feishu_enabled')
        self.load_settings()
        QMessageBox.information(self, '重置完成', '飞书配置已重置为默认值')
    
    def _test_map(self):
        key = self.amap_key.text() if self.map_provider.currentText() == 'amap' else self.tianditu_key.text()
        success, msg = ConfigValidator.validate_amap_key(key)
        self.map_status.setText(msg)
        self.map_status.setStyleSheet('color: green;' if success else 'color: red;')
    
    def _save_map(self):
        self.settings_mgr.save('map_provider', self.map_provider.currentText())
        self.settings_mgr.save('amap_key', self.amap_key.text())
        self.settings_mgr.save('tianditu_key', self.tianditu_key.text())
        QMessageBox.information(self, '保存成功', '地图配置已保存')
    
    def _reset_map(self):
        self.settings_mgr.reset_to_default('map_provider')
        self.settings_mgr.reset_to_default('amap_key')
        self.settings_mgr.reset_to_default('tianditu_key')
        self.load_settings()
        QMessageBox.information(self, '重置完成', '地图配置已重置为默认值')
    
    def _save_crawler(self):
        self.settings_mgr.save('crawler_enabled', self.crawler_enabled.isChecked())
        self.settings_mgr.save('crawler_interval_hours', self.crawler_interval.value())
        sources = {'baidu': self.source_baidu.isChecked(), 'sina': self.source_sina.isChecked(), '163': self.source_163.isChecked(), 'xiangshan': self.source_xiangshan.isChecked()}
        self.settings_mgr.save('crawler_sources', sources)
        QMessageBox.information(self, '保存成功', '爬虫配置已保存')
    
    def _reset_crawler(self):
        self.settings_mgr.reset_to_default('crawler_enabled')
        self.settings_mgr.reset_to_default('crawler_interval_hours')
        self.settings_mgr.reset_to_default('crawler_sources')
        self.load_settings()
        QMessageBox.information(self, '重置完成', '爬虫配置已重置为默认值')
    
    def _save_alert(self):
        self.settings_mgr.save('alert_enabled', self.alert_enabled.isChecked())
        self.settings_mgr.save('alert_high_threshold', self.alert_high.value())
        self.settings_mgr.save('alert_medium_threshold', self.alert_medium.value())
        QMessageBox.information(self, '保存成功', '预警规则已保存')
    
    def _reset_alert(self):
        self.settings_mgr.reset_to_default('alert_enabled')
        self.settings_mgr.reset_to_default('alert_high_threshold')
        self.settings_mgr.reset_to_default('alert_medium_threshold')
        self.load_settings()
        QMessageBox.information(self, '重置完成', '预警规则已重置为默认值')
    
    def _save_data(self):
        self.settings_mgr.save('obsidian_path', self.obsidian_path.text())
        self.settings_mgr.save('db_path', self.db_path.text())
        self.settings_mgr.save('backup_path', self.backup_path.text())
        QMessageBox.information(self, '保存成功', '数据目录配置已保存')
    
    def _reset_data(self):
        self.settings_mgr.reset_to_default('obsidian_path')
        self.settings_mgr.reset_to_default('db_path')
        self.settings_mgr.reset_to_default('backup_path')
        self.load_settings()
        QMessageBox.information(self, '重置完成', '数据目录已重置为默认值')
    
    def _export_config(self):
        path = self.settings_mgr.export_config()
        QMessageBox.information(self, '导出成功', f'配置已导出到:\n{path}')
    
    def _test_ai(self):
        success, msg = ConfigValidator.validate_ai_key(self.ai_api_key.text(), self.ai_model.currentText())
        self.ai_status.setText(msg)
        self.ai_status.setStyleSheet('color: green;' if success else 'color: red;')
    
    def _save_ai(self):
        self.settings_mgr.save('ai_model', self.ai_model.currentText())
        self.settings_mgr.save('ai_api_key', self.ai_api_key.text())
        self.settings_mgr.save('ai_temperature', self.ai_temperature.value())
        QMessageBox.information(self, '保存成功', 'AI模型配置已保存')
    
    def _reset_ai(self):
        self.settings_mgr.reset_to_default('ai_model')
        self.settings_mgr.reset_to_default('ai_api_key')
        self.settings_mgr.reset_to_default('ai_temperature')
        self.load_settings()
        QMessageBox.information(self, '重置完成', 'AI模型配置已重置为默认值')
